import type { NodeDefinition } from "@workflow/types";

export const httpRequestNode: NodeDefinition = {
  type: "http-request",
  name: "HTTP Request",
  description: "Make HTTP requests to APIs and services",
  category: "action",
  icon: "globe",
  version: 2,
  inputs: [{ name: "main", label: "Input", type: "main" }],
  outputs: [
    { name: "main", label: "Output", type: "main" },
    { name: "error", label: "Error", type: "error" },
  ],
  parameters: [
    {
      name: "method",
      label: "Method",
      type: "options",
      required: true,
      default: "GET",
      options: [
        { label: "GET", value: "GET" },
        { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" },
        { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
        { label: "HEAD", value: "HEAD" },
      ],
      description: "HTTP method to use",
    },
    {
      name: "url",
      label: "URL",
      type: "string",
      required: true,
      description:
        "Absolute URL to call. Supports expressions, e.g. {{ $json.endpoint }}",
    },
    {
      name: "authentication",
      label: "Authentication",
      type: "options",
      required: true,
      default: "none",
      options: [
        { label: "None", value: "none" },
        { label: "Basic", value: "basic" },
        { label: "Bearer / OAuth2", value: "bearer" },
        { label: "API Key", value: "apiKey" },
      ],
      description:
        "Authentication mode. Credential payload is mapped at runtime based on this value.",
    },
    {
      name: "headers",
      label: "Headers",
      type: "json",
      required: false,
      default: {},
      description:
        "Request headers object. Supports expressions in string values.",
    },
    {
      name: "query",
      label: "Query Parameters",
      type: "json",
      required: false,
      default: {},
      description:
        "Query params object appended to URL. Supports expressions in values.",
    },
    {
      name: "body",
      label: "Body",
      type: "json",
      required: false,
      default: {},
      description:
        "Request body for non-GET methods. Object/string supported. Expressions allowed.",
    },
    {
      name: "timeout_ms",
      label: "Timeout (ms)",
      type: "number",
      required: false,
      default: 30000,
      description: "Request timeout in milliseconds",
    },
    {
      name: "response_format",
      label: "Response Format",
      type: "options",
      required: true,
      default: "auto",
      options: [
        { label: "Auto", value: "auto" },
        { label: "JSON", value: "json" },
        { label: "Text", value: "text" },
        { label: "Raw (base64)", value: "raw" },
      ],
      description: "How response body should be parsed",
    },
    {
      name: "retry",
      label: "Retry Options",
      type: "json",
      required: false,
      default: {
        enabled: false,
        attempts: 3,
        delay_ms: 500,
        backoff_factor: 1.5,
        retry_on_status: [429, 500, 502, 503, 504],
        retry_on_network_error: true,
      },
      description:
        "Retry policy. Example: { enabled:true, attempts:3, delay_ms:500, backoff_factor:1.5 }",
    },
    {
      name: "pagination",
      label: "Pagination",
      type: "json",
      required: false,
      default: {
        enabled: false,
        type: "none",
        max_pages: 1,
        page_param: "page",
        page_start: 1,
        page_size_param: "limit",
        page_size: 50,
        offset_param: "offset",
        offset_start: 0,
        offset_step: 50,
        cursor_param: "cursor",
        cursor_path: "next_cursor",
        has_more_path: "has_more",
        items_path: "",
        next_link_header: "link",
      },
      description:
        "Pagination config. Supported types: none, page, offset, cursor, link-header",
    },
  ],
};
