import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { format, formatDistanceToNow } from 'date-fns';
import { Link } from 'react-router-dom';
import { useExecutions } from '../hooks/use-executions';
export default function Executions() {
    const { data: executions, isLoading, error } = useExecutions();
    if (error) {
        return (_jsx("div", { className: "p-8", children: _jsx("div", { className: "rounded-md bg-[hsl(var(--destructive)/0.1)] p-4 border border-[hsl(var(--destructive)/0.2)]", children: _jsxs("p", { className: "text-[hsl(var(--destructive))]", children: ["Failed to load executions: ", error.message] }) }) }));
    }
    return (_jsxs("div", { className: "p-8 space-y-6 max-w-6xl mx-auto", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold tracking-tight text-[hsl(var(--foreground))]", children: "Executions" }), _jsx("p", { className: "text-[hsl(var(--muted-foreground))] mt-1", children: "History and logs of your past workflow runs." })] }), isLoading ? (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx("div", { className: "h-8 w-8 animate-spin rounded-full border-4 border-[hsl(var(--primary))] border-t-transparent" }) })) : executions?.length === 0 ? (_jsxs("div", { className: "rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--secondary)/0.3)] p-12 text-center shadow-sm", children: [_jsx("div", { className: "mx-auto h-12 w-12 text-[hsl(var(--muted-foreground))] opacity-50 mb-4", children: _jsx("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: _jsx("polyline", { points: "22 12 18 12 15 21 9 3 6 12 2 12" }) }) }), _jsx("h3", { className: "text-lg font-medium text-[hsl(var(--foreground))]", children: "No past executions" }), _jsx("p", { className: "mt-1 text-sm text-[hsl(var(--muted-foreground))]", children: "This list will populate when you run your workflows manually or via triggers." })] })) : (_jsx("div", { className: "rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))] overflow-hidden shadow-sm", children: _jsxs("table", { className: "w-full text-sm text-left", children: [_jsx("thead", { className: "bg-[hsl(var(--secondary)/0.5)] text-[hsl(var(--muted-foreground))] border-b border-[hsl(var(--border))]", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-4 font-medium", children: "Status" }), _jsx("th", { className: "px-6 py-4 font-medium", children: "Workflow" }), _jsx("th", { className: "px-6 py-4 font-medium", children: "Started" }), _jsx("th", { className: "px-6 py-4 font-medium", children: "Duration" }), _jsx("th", { className: "px-6 py-4 font-medium text-right", children: "Trigger" })] }) }), _jsx("tbody", { className: "divide-y divide-[hsl(var(--border))]", children: executions?.map((exec) => {
                                const start = new Date(exec.started_at);
                                const end = exec.completed_at ? new Date(exec.completed_at) : null;
                                const durationMs = end ? end.getTime() - start.getTime() : null;
                                return (_jsxs("tr", { className: "hover:bg-[hsl(var(--secondary)/0.3)] transition-colors", children: [_jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-center gap-2", children: [exec.status === 'completed' && _jsx("span", { className: "h-2 w-2 rounded-full bg-[hsl(var(--primary))]" }), exec.status === 'failed' && _jsx("span", { className: "h-2 w-2 rounded-full bg-[hsl(var(--destructive))]" }), exec.status === 'running' && _jsx("span", { className: "h-2 w-2 rounded-full bg-blue-500 animate-pulse" }), exec.status === 'pending' && _jsx("span", { className: "h-2 w-2 rounded-full bg-gray-400" }), _jsx("span", { className: "capitalize font-medium text-[hsl(var(--foreground))]", children: exec.status })] }) }), _jsx("td", { className: "px-6 py-4 font-medium", children: _jsx(Link, { to: `/workflow/${exec.workflow_id}`, className: "text-[hsl(var(--foreground))] hover:underline", children: exec.workflow?.name || 'Unknown Workflow' }) }), _jsxs("td", { className: "px-6 py-4 text-[hsl(var(--muted-foreground))]", children: [format(start, 'MMM d, HH:mm:ss'), _jsx("div", { className: "text-xs opacity-70", children: formatDistanceToNow(start, { addSuffix: true }) })] }), _jsx("td", { className: "px-6 py-4 text-[hsl(var(--muted-foreground))] font-mono", children: durationMs !== null ? `${durationMs}ms` : '-' }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsx("span", { className: "inline-flex items-center rounded-md bg-[hsl(var(--secondary))] px-2 py-1 text-xs font-medium text-[hsl(var(--muted-foreground))] ring-1 ring-inset ring-[hsl(var(--border))]", children: exec.trigger_type }) })] }, exec.id));
                            }) })] }) }))] }));
}
